easy = [
    "Cat", "Dog", "Cow", "Horse", "Lion", "Tiger", "Elephant", "Monkey", "Fish", 
    "Shark", "Dolphin", "Bear", "Penguin", "Rabbit", "Chicken", "Goat", "Sheep", 
    "Pig", "Duck", "Frog", "Owl", "Deer", "Kangaroo", "Koala", "Zebra", "Giraffe", 
    "Snake", "Cheetah", "Eagle", "Hawk", "Falcon", "Fox", "Wolf", "Turtle", 
    "Crocodile", "Alligator", "Parrot", "Bat", "Hamster", "Rat", "Squirrel", 
    "Hippopotamus", "Rhinoceros", "Whale", "Octopus", "Panda", "Peacock", 
    "Swan", "Goldfish", "Sea lion", "Seal", "Chimpanzee", "Gorilla", "Leopard", 
    "Raccoon", "Moose", "Buffalo", "Bee", "Butterfly", "Ladybug", "Spider", 
    "Crab", "Lobster", "Horse", "Donkey", "Camel", "Polar bear", "Pigeon", 
    "Pelican", "Flamingo", "Beaver", "Otter", "Turkey", "Sparrow", "Crow", 
    "Robin", "Vulture", "Antelope", "Llama", "Hedgehog", "Porcupine", 
    "Chameleon", "Iguana", "Toad", "Salmon", "Trout", "Starfish", "Jellyfish", 
    "Seahorse", "Koala", "Wombat", "Platypus", "Ostrich", "Emu", "Albatross", 
    "Falcon", "Skunk", "Coyote", "Jackal", "Lynx", "Meerkat", "Hummingbird", 
    "Pigeon", "Parakeet", "Walrus", "Woodpecker", "Mallard", "Grouse", 
    "Shrew", "Panther", "Bison", "Armadillo", "Ox", "Fox", "Gannet", "Mole", 
    "Stork", "Snipe", "Termite", "Tortoise"
]

medium = [
    "Antelope", "Badger", "Bald eagle", "Bobcat", "Bison", "Boar", "Bonobo", 
    "Caribou", "Cassowary", "Cockatoo", "Cobra", "Cougar", "Crane", "Dingo", 
    "Dromedary", "Echidna", "Elk", "Gazelle", "Gibbon", "Gila monster", "Gnu", 
    "Harpy eagle", "Hawk", "Heron", "Honey badger", "Ibex", "Jaguar", "Javelina", 
    "Kingfisher", "Komodo dragon", "Kudu", "Lamprey", "Lemming", "Lemur", 
    "Lynx", "Manatee", "Mandrill", "Marmoset", "Marten", "Mink", "Mongoose", 
    "Narwhal", "Ocelot", "Okapi", "Orangutan", "Oryx", "Pangolin", "Peregrine falcon", 
    "Quail", "Quokka", "Rattlesnake", "Reindeer", "Roadrunner", "Saiga", 
    "Secretary bird", "Serval", "Shrew", "Sloth", "Snow leopard", "Stoat", 
    "Tapir", "Tasmanian devil", "Tamarin", "Toucan", "Tuatara", "Vicuna", 
    "Warthog", "Wildebeest", "Wolverine", "Yak", "Zebu", "Anaconda", 
    "Angelfish", "Axolotl", "Barracuda", "Betta fish", "Blue jay", "Capybara", 
    "Caracal", "Civet", "Cuscus", "Dhole", "Dugong", "Emperor penguin", 
    "Flying squirrel", "Frigatebird", "Frilled lizard", "Gaur", "Giant anteater", 
    "Giant tortoise", "Glass frog", "Golden eagle", "Golden lion tamarin", 
    "Groundhog", "Grouper", "Guinea pig", "Horseshoe crab", "Hydra", "Ibis", 
    "Indian elephant", "Indri", "Jackrabbit", "Jellyfish", "Jerboa", "Katydid", 
    "Kiwi", "Kookaburra", "Krill", "Ladybug", "Lemming", "Liger", "Lionfish", 
    "Little owl", "Manta ray", "Marlin", "Nightingale", "Orca", "Pacu", 
    "Peccary", "Pika", "Piranha", "Puffin", "Quetzal", "Red panda", "Rhea", 
    "Saola", "Scorpion", "Shoebill", "Skink", "Sperm whale", "Spoonbill", 
    "Spotted hyena", "Sugar glider", "Thylacine", "Tibetan mastiff", 
    "Velociraptor", "Vicuna", "Viper", "Wallaby", "Wapiti", "Wattled crane", 
    "Weasel", "Whiptail lizard", "Wolverine", "Woodcock"
]


difficult = [
    "Aardvark", "Aye-aye", "Binturong", "Bilby", "Bushbaby", "Cane toad", 
    "Caracara", "Cassowary", "Caterpillar", "Cuscus", "Drongo", "Dugong", 
    "Eland", "Fossa", "Galago", "Genet", "Gerenuk", "Glaucus", "Hoatzin", 
    "Iriomote cat", "Kakapo", "Kangaroo rat", "Kea", "Kinkajou", "Kipunji", 
    "Kookaburra", "Markhor", "Muntjac", "Numbat", "Olingo", "Onager", 
    "Paca", "Pangolin", "Patagonian mara", "Potto", "Proboscis monkey", 
    "Quagga", "Quoll", "Red-shanked douc", "Saki", "Sand cat", "Sifaka", 
    "Solenodon", "Sunda pangolin", "Sun bear", "Takin", "Tamandua", "Tanuki", 
    "Tarsier", "Uakari", "Vaquita", "Vicuña", "Vine snake", "Waterbuck", 
    "Xerus", "Zebu", "Zorilla", "Zorua", "Arapaima", "Arctic hare", "Basilisk", 
    "Bird of paradise", "Blobfish", "Bongo", "Bontebok", "Bushmaster", 
    "Capuchin monkey", "Coati", "Colobus monkey", "Colugo", "Cuscus", "Dassie", 
    "Duiker", "Dunnart", "Ermine", "Fennec fox", "Ferruginous hawk", 
    "Fishing cat", "Flounder", "Flying fish", "Fossa", "Gharial", "Gilamonster", 
    "Goanna", "Goblin shark", "Goral", "Hagfish", "Hellbender", "Hyrax", 
    "Ibex", "Ibisbill", "Irukandji jellyfish", "Jabiru", "Japanese macaque", 
    "Kagu", "Kermode bear", "Kudu", "Lammergeier", "Leatherback turtle", 
    "Linsang", "Mara", "Margay", "Masked owl", "Matamata", "Monk seal", 
    "Mudskipper", "Numbat", "Ocelot", "Oncilla", "Oxpecker", "Pangolin", 
    "Pika", "Pine marten", "Potoroo", "Proboscis monkey", "Puffin", 
    "Quokka", "Raccoon dog", "Red-shanked douc", "Ringtail", "Saola", 
    "Sifaka", "Skink", "Solenodon", "Spectacled bear", "Sun bear", 
    "Tarsier", "Tuatara"]



professional = [
    "Addax", "Arapaima", "Argali", "Axolotl", "Baiji", "Barasingha", "Basilisk", 
    "Bat-eared fox", "Beira antelope", "Betta fish", "Bongo", "Bontebok", 
    "Bushmaster", "Cacomistle", "Caiman lizard", "Capuchin monkey", "Caracal", 
    "Civet", "Colobus monkey", "Colugo", "Dhole", "Dibbler", "Dugong", 
    "Eastern quoll", "Fennec fox", "Fishing cat", "Fossa", "Gaur", "Gharial", 
    "Gilamonster", "Goanna", "Goral", "Greater bilby", "Grison", "Gudgeon", 
    "Harbor porpoise", "Hartebeest", "Himalayan tahr", "Honduran white bat", 
    "Hoopoe", "Horseshoe crab", "Ibex", "Indian cobra", "Irukandji jellyfish", 
    "Jerboa", "Kagu", "Kermode bear", "Kinkajou", "Kipunji", "Kowari", "Kudu", 
    "Lamprey", "Leatherback turtle", "Lechwe", "Linsang", "Maned wolf", 
    "Markhor", "Matamata turtle", "Mara", "Margay", "Masked palm civet", 
    "Monk seal", "Mudskipper", "Naked mole rat", "Narwhal", "Numbat", 
    "Olingo", "Oncilla", "Oxpecker", "Pangolin", "Patagonian mara", "Pine marten", 
    "Potoroo", "Przewalski's horse", "Pudu", "Quagga", "Quokka", "Quoll", 
    "Raccoon dog", "Red-shanked douc", "Ringtail", "Saola", "Sea cucumber", 
    "Sifaka", "Skink", "Solenodon", "Spectacled bear", "Spoonbill", "Sun bear", 
    "Takin", "Tamandua", "Tarsier", "Thylacine", "Tuatara", "Vaquita", 
    "Vicuña", "Vine snake", "Wapiti", "Water chevrotain", "Water deer", 
    "Wattled crane", "Xerus", "Yabby", "Zebra finch", "Zorilla", "Zorua", 
    "Zebu", "Arctic fox", "Binturong", "Bottlenose dolphin", "Bush viper", 
    "Clouded leopard", "Dugong", "Fennec fox", "Flying fox", "Giant clam", 
    "Giant salamander", "Goblin shark", "Golden snub-nosed monkey", 
    "Great argus", "Hellbender", "Humphead wrasse", "Iridescent shark", 
    "Kakapo", "Kiang", "Leafy seadragon", "Lynx", "Markhor", "Matamata", 
    "Mountain pygmy possum", "Okapi", "Onager", "Pallas's cat", "Pied tamarin", 
    "Pink fairy armadillo", "Proboscis monkey", "Saddleback tamarin", 
    "Shovel-nosed snake", "Shoebill", "Silkie chicken", "Spoonbill", "Sunda pangolin", 
    "Tayra", "Tuatara", "Vicuña", "Viperfish", "Wolverine", "Yellow mongoose"
]

impossible = [
    "Aardwolf", "Addra gazelle", "Aldabra tortoise", "Annamite striped rabbit", 
    "Bawean deer", "Bearded saki", "Binturong", "Black-footed ferret", "Blue glaucus", 
    "Bongo", "Bristle-thighed curlew", "Cacique", "Caracal", "Cave swiftlet", 
    "Chinese water deer", "Coati", "Coquerel's sifaka", "Cotton-top tamarin", 
    "Crabeater seal", "Crested porcupine", "Cuvier's gazelle", "Dhole", 
    "Eastern quoll", "Falanouc", "Fennec", "Fossa", "Giant otter", "Golden lion tamarin", 
    "Grison", "Hamadryas baboon", "Hartebeest", "Hoatzin", "Iriomote cat", 
    "Javan rhino", "Kea", "Kowari", "Kudu", "Lechwe", "Linsang", "Livingstone's fruit bat", 
    "Maned wolf", "Markhor", "Matamata turtle", "Moon bear", "Nabarlek", 
    "Naked mole rat", "Numbat", "Olinguito", "Pacu", "Pudu", "Pygmy hippopotamus", 
    "Quagga", "Quoll", "Saiga", "Saola", "Secretary bird", "Sunda pangolin", 
    "Tarsier", "Tibetan antelope", "Vicuña", "Visayan spotted deer", 
    "Wattled curassow", "Xoloitzcuintli", "Zanzibar red colobus", "Zebra duiker", 
    "Zeren", "Zokor", "Zorilla", "Aye-aye", "Babirusa", "Bearded vulture", 
    "Binturong", "Bongo", "Bush dog", "Civet cat", "Dusky dolphin", "Fossa", 
    "Frogfish", "Giant pangolin", "Giant squid", "Goblin shark", "Hairy frog", 
    "Iridescent shark", "Kakapo", "Kermode bear", "Kowari", "Lesser kudu", 
    "Long-beaked echidna", "Markhor", "Matamata", "Monito del monte", 
    "Numbat", "Oncilla", "Proboscis monkey", "Quagga", "Red-handed tamarin", 
    "Shovel-nosed snake", "Spectacled caiman", "Tasmanian tiger", "Thorny devil", 
    "Vaquita", "Visayan warty pig", "Western long-beaked echidna", "Yeti crab"
]


impossible = [
    "Aardwolf", "Addra gazelle", "Aldabra tortoise", "Annamite striped rabbit", 
    "Bawean deer", "Bearded saki", "Binturong", "Black-footed ferret", "Blue glaucus", 
    "Bongo", "Bristle-thighed curlew", "Cacique", "Caracal", "Cave swiftlet", 
    "Chinese water deer", "Coati", "Coquerel's sifaka", "Cotton-top tamarin", 
    "Crabeater seal", "Crested porcupine", "Cuvier's gazelle", "Dhole", 
    "Eastern quoll", "Falanouc", "Fennec", "Fossa", "Giant otter", "Golden lion tamarin", 
    "Grison", "Hamadryas baboon", "Hartebeest", "Hoatzin", "Iriomote cat", 
    "Javan rhino", "Kea", "Kowari", "Kudu", "Lechwe", "Linsang", "Livingstone's fruit bat", 
    "Maned wolf", "Markhor", "Matamata turtle", "Moon bear", "Nabarlek", 
    "Naked mole rat", "Numbat", "Olinguito", "Pacu", "Pudu", "Pygmy hippopotamus", 
    "Quagga", "Quoll", "Saiga", "Saola", "Secretary bird", "Sunda pangolin", 
    "Tarsier", "Tibetan antelope", "Vicuña", "Visayan spotted deer", 
    "Wattled curassow", "Xoloitzcuintli", "Zanzibar red colobus", "Zebra duiker", 
    "Zeren", "Zokor", "Zorilla", "Aye-aye", "Babirusa", "Bearded vulture", 
    "Binturong", "Bongo", "Bush dog", "Civet cat", "Dusky dolphin", "Fossa", 
    "Frogfish", "Giant pangolin", "Giant squid", "Goblin shark", "Hairy frog", 
    "Iridescent shark", "Kakapo", "Kermode bear", "Kowari", "Lesser kudu", 
    "Long-beaked echidna", "Markhor", "Matamata", "Monito del monte", 
    "Numbat", "Oncilla", "Proboscis monkey", "Quagga", "Red-handed tamarin", 
    "Shovel-nosed snake", "Spectacled caiman", "Tasmanian tiger", "Thorny devil", 
    "Vaquita", "Visayan warty pig", "Western long-beaked echidna", "Yeti crab"
]


animals = [easy, medium, difficult, professional, impossible]
